name             'capistrano'
maintainer       'Matt Chun-Lum'
maintainer_email 'mchunlum@gmail.com'
license          'All rights reserved'
description      'Installs/Configures capistrano'
long_description 'Installs/Configures capistrano'
version          '0.1.0'
